export default {
    LOADING_ORDER_DRAFT: 'ORDER_DRAFT/LOADING_ORDER_DRAFT',
    LOAD_ORDER_DRAFT_SUCCESS: 'ORDER_DRAFT/LOAD_ORDER_DRAFT_SUCCESS',
    LOAD_ORDER_DRAFT_FAILED: 'ORDER_DRAFT/LOAD_ORDER_DRAFT_FAILED',
    DELETE_ORDER_DRAFT_SUCCESS: 'ORDER_DRAFT/DELETE_ORDER_DRAFT_SUCCESS',
};
